#DEFINE 	VFP7_FIELD_TYPES		'CDTNFIBYLMG'
#DEFINE 	VFP7_FIELD_TYPES_FIXED_LEN		'DTIBLMG'
#DEFINE 	VFP7_FIELD_TYPES_WITH_DEC		'NFB'

#DEFINE 	VFP9_FIELD_TYPES		'WCYDTBGILMNFQV'
#DEFINE 	VFP9_FIELD_TYPES_FIXED_LEN		'WYDTGILM' && B
#DEFINE 	VFP9_FIELD_TYPES_FIXED_LEN_1B		'L'
#DEFINE 	VFP9_FIELD_TYPES_FIXED_LEN_4B		'WGIM'
#DEFINE 	VFP9_FIELD_TYPES_FIXED_LEN_8B		'YDTB'
#DEFINE 	VFP9_FIELD_TYPES_WITH_DEC		'NFB'
